/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.Contribution.Contribution;
import Business.Contributor.Contributor;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author murali
 */
public class ApproveRejectIndContributionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveRejectIndContributionJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount user;
    
    public ApproveRejectIndContributionJPanel(JPanel userProcessContainer,UserAccount user, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
        
        populateIndividualContribution();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIndividualContribution = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Manage Individual Contribution");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 55, -1, -1));

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btnApprove.setText("Approve");
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        btnReject.setText("Reject");
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        tblIndividualContribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Item", "Quantity", "Expiry Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblIndividualContribution);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 119, 614, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIndividualContribution;
    // End of variables declaration//GEN-END:variables

    private void populateIndividualContribution() {
        
        DefaultTableModel model = (DefaultTableModel) tblIndividualContribution.getModel();
        
        model.setRowCount(0);
       
        for (Contributor admin:system.getContributorDirectory().getContributorList()){

               if ("Business.Role.VolunteerRole".equals(user.getRole().getClass().getName())) {
               for(Contribution contribution:admin.getContribution()){
                Object[] row = new Object[5];
                row[0] = contribution;
                row[1] = contribution.getItem();
                row[2] = contribution.getQuantity();
                row[3] = contribution.getExpiryDate();
                row[4] = contribution.getStatus();
                model.addRow(row);
               }
                
            }
    }
        
    }
}
