/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yashwanthsridharan
 */
public class VolunteerAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VoluteerAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;

    public VolunteerAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        jLabel1.setText("Welcome "+account.getUsername());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAppRejStoreContribution = new javax.swing.JButton();
        btnAppRejIndContribution = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Welcome Volunteer!");

        btnAppRejStoreContribution.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnAppRejStoreContribution.setForeground(new java.awt.Color(67, 0, 163));
        btnAppRejStoreContribution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/view.png"))); // NOI18N
        btnAppRejStoreContribution.setText("View Store Contribution");
        btnAppRejStoreContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppRejStoreContributionActionPerformed(evt);
            }
        });

        btnAppRejIndContribution.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnAppRejIndContribution.setForeground(new java.awt.Color(67, 0, 163));
        btnAppRejIndContribution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/view.png"))); // NOI18N
        btnAppRejIndContribution.setText("View Individual Contribution");
        btnAppRejIndContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppRejIndContributionActionPerformed(evt);
            }
        });

        btnViewProfile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnViewProfile.setForeground(new java.awt.Color(67, 0, 163));
        btnViewProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/view.png"))); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAppRejIndContribution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAppRejStoreContribution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewProfile)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProfile)
                    .addComponent(jLabel1))
                .addGap(87, 87, 87)
                .addComponent(btnAppRejStoreContribution)
                .addGap(30, 30, 30)
                .addComponent(btnAppRejIndContribution)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppRejStoreContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppRejStoreContributionActionPerformed
        // TODO add your handling code here:
        ApproveRejectStoreContributionJPanel arscjp = new ApproveRejectStoreContributionJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("Manage Store Contribution", arscjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAppRejStoreContributionActionPerformed

    private void btnAppRejIndContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppRejIndContributionActionPerformed
        // TODO add your handling code here:
        ApproveRejectIndContributionJPanel aricjp = new ApproveRejectIndContributionJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("Manage Individual Contribution", aricjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAppRejIndContributionActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        ViewVolunteerProfileJPanel vvpjp = new ViewVolunteerProfileJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("View Profile", vvpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppRejIndContribution;
    private javax.swing.JButton btnAppRejStoreContribution;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
