/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryAdminRole;

import Business.Contribution.Contribution;
import Business.DeliveryAgent.DeliveryAgent;
import Business.EcoSystem;
import Business.Products.Product;
import Business.Products.ProductList;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class AssignDeliveryAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignDeliveryAgencyJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    UserAccount user;
    Contribution contribution;
    WorkRequest workRequest;
    public AssignDeliveryAgencyJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, Contribution contribution,WorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = account;
        this.system = system;
        this.contribution = contribution;
        this.workRequest = workRequest;
        populateDeliveryAgencyTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliveryAgency = new javax.swing.JTable();
        BackBtn = new javax.swing.JButton();
        btnAssignDeliveryAgency = new javax.swing.JButton();

        tblDeliveryAgency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDeliveryAgency);

        BackBtn.setText("<< Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        btnAssignDeliveryAgency.setText("Assign Order");
        btnAssignDeliveryAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDeliveryAgencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BackBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAssignDeliveryAgency)
                        .addGap(246, 246, 246))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(BackBtn)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAssignDeliveryAgency)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void btnAssignDeliveryAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDeliveryAgencyActionPerformed

        int selectedRow = tblDeliveryAgency.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String userName = (String) tblDeliveryAgency.getValueAt(selectedRow, 0);
            
            for(UserAccount ua1 : system.getUserAccountDirectory().getUserAccountList()){
                if(ua1.getUsername().equals(userName)){
                    contribution.setStatus("Assigned to Agency");
                    workRequest.setStatus("Assigned to Agency");
                    workRequest.setDeliveryAgencyAdminName(ua1.getUsername());
                    ua1.getWorkQueue().addWorkRequesttoQueue(workRequest);
                    
                }
            }
            
        }
    }

    private void populateDeliveryAgencyTable() {
        DefaultTableModel model = (DefaultTableModel) tblDeliveryAgency.getModel();

        model.setRowCount(0);
        for (DeliveryAgent admin : system.getDeliveryAgentDirectory().getDeliveryAgentDirectory()) {
            JOptionPane.showMessageDialog(null, system.getDeliveryAgentDirectory().getDeliveryAgentDirectory().size());

            for (DeliveryAgent deliveryAgent : system.getDeliveryAgentDirectory().getDeliveryAgentDirectory()) {
                Object[] row = new Object[1];
                row[0] = deliveryAgent.getUserName();
                model.addRow(row);
            }

        }
    }//GEN-LAST:event_btnAssignDeliveryAgencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton btnAssignDeliveryAgency;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeliveryAgency;
    // End of variables declaration//GEN-END:variables
}
